Initial version of the certificate generation tool for client authentication. It still requires more adjusts.

diff --git a/ssl-auth/create-user b/ssl-auth/create-user
--- a/ssl-auth/create-user
+++ b/ssl-auth/create-user
@@ -1,6 +1,7 @@
+#!/bin/bash
 # BSD 3-Clause License
 # 
-# Copyright (c) 2018, Fabio Jun Takada Chino
+# Copyright (c) 2018-2019, Fabio Jun Takada Chino
 # All rights reserved.
 # 
 # Redistribution and use in source and binary forms, with or without
@@ -28,37 +29,56 @@
 # OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 # OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-# Deterine the home directory of the script
-MY_HOME=$(dirname "$0")
-pushd "$MY_HOME" > /dev/null
-MY_HOME=$(pwd)
-popd > /dev/null
+# Include the 
+. $(dirname "$0")/common.inc
 
-# Execution timestamp
-TIMESTAMP=$(date +%Y%m%d)
+# Check the parameters
+if [ $# -ne 1 ] ; then
+	echo "Usage: $0 <user name>"
+	exit 1
+fi
 
-# Files and directories
-CA_PRIVATE_DIR=$MY_HOME/private
-CA_CERT_DIR=$MY_HOME/certs
-CA_REVOKED_DIR=$MY_HOME/certs/revoked
-CA_CONF_DIR=$MY_HOME/conf
-CA_CRL_DIR=$MY_HOME/crl
-CA_DB_DIR=$MY_HOME/db
-CA_CERT_DB_DIR=$CA_DB_DIR/certs
-CA_USER_DIR=$MY_HOME/users
+USERNAME=$1
+USER_DIR=$CA_USER_DIR/$USERNAME
+USER_KEY=$USER_DIR/privkey.pem
+USER_CSR=$USER_DIR/$USERNAME.csr
+USER_CER=$USER_DIR/$USERNAME.cer
+USER_P12=$USER_DIR/$USERNAME.p12
 
-# Keys and configuration
-CA_PRIVATE_KEY=$CA_PRIVATE_DIR/cakey.pem
-CA_CERTIFICATE=$CA_CERT_DIR/cacert.pem
-CA_CONFIG_FILE=$CA_CONF_DIR/ca.cnf
-CA_SERIAL_FILE=$CA_DB_DIR/serial.txt
-CA_INDEX_FILE=$CA_DB_DIR/index.txt
-CA_CRL_NUMBER_FILE=$CA_DB_DIR/crlnumber.txt
-CA_CRL_FILE=$CA_CRL_DIR/ca.crl
+if [ -d $USER_DIR ]; then
+	echo "$USERNAME already exists."
+	exit 2
+fi
 
-# Constants
-CA_KEY_ENC=-aes256
-CA_KEY_SIZE=2048
-CA_CERT_DAYS=7300
+mkdir -p "$USER_DIR"
+
+# Create the user password
+USER_PASSWD=$(openssl rand -base64 15)
+
+if openssl genrsa -out $USER_KEY $CA_KEY_SIZE -password pass:$USER_PASSWD ; then
+	echo "Private key for the user $USERNAME created."
+else
+	echo "Unable to create the private key for the user $USERNAME."
+	exit 2
+fi
+
+if openssl req -new -key $USER_KEY -out $USER_CSR -subj "/CN=$USERNAME/O=$USERNAME/OU=$USERNAME"; then
+	echo "CSR for $USERNAME created."
+else
+	echo "Unable to create the CSR for the user $USERNAME."
+	exit 2
+fi
+
+cp $USER_CSR $CA_CERT_DIR/$USERNAME.csr
+if ./sign $USERNAME ; then
+	echo "Certificate signed."
+	cp $CA_CERT_DIR/$USERNAME.cer $USER_CER
+else
+	echo "Unable to sign the certificate."
+	exit 1
+fi
+
+openssl pkcs12 -export -inkey $USER_KEY -in $USER_CER -out $USER_P12 -password pass:$USER_PASSWD
+echo $USER_PASSWD
 
 
